#!/usr/bin/ruby

require './Matrix'
require './Gauss'
require './Regressions'

mat = Matrix.new
mat.set( [
	[1, 1, 1],
	[2, 4, 1],
	[3, 9, 1],
	[4, 16, 1],
	[5, 25, 1]
] )

res = Matrix.new
res.set([[4], [5], [7], [10], [15]])

coefs = poylnomialRegression(mat, res)
puts "#{coefs}"
